### ISSUE TITLE
No such module 'libtdjson'

### ISSUE THREAD

**Issue by liuxingyubm** [up9cloud/ios-libtdjson#2]
I created my own PodSpec, but it still doesn't work
<img width="1282" alt="WeChat3a8f20eda3917796ff10d597a0598de7" src="https://user-images.githubusercontent.com/100563041/155953486-11f3f7de-4a8d-4d93-a257-d9e05da4802e.png">
 It's my first time to use this. Don't know how to use it

**Comment by up9cloud** [comment]
You have to manually add modulemap file and set flag for the compiler.
If you're not familiar with setting up xcconfig, I would like to suggest you checking https://github.com/up9cloud/flutter_libtdjson. There is a completely example for flutter.
