### ISSUE TITLE
Library not loaded: @rpath/libtdjson.dylib

### ISSUE THREAD

**Issue by liuxingyubm** [up9cloud/ios-libtdjson#3]
I have already pod 'libtdjson','0.2.2
<img width="308" alt="WeChatde48d016d5a60672e96975e4859dc53d" src="https://user-images.githubusercontent.com/100563041/155962526-f37c4de3-00b8-4500-ad7e-eed5bcadf15e.png">
'Library not loaded: @rpath/libtdjson.dylib
  Referenced from: /private/var/containers/Bundle/Application/FF2B21C5-C56D-4843-A33D-B05067617415/duolaimi.app/duolaimi
  Reason: tried: '/usr/lib/system/introspection/libtdjson.dylib' (no such file), '/usr/lib/swift/libtdjson.dylib' (no such file), '/private/var/containers/Bundle/Application/FF2B21C5-C56D-4843-A33D-B05067617415/duolaimi.app/Frameworks/libtdjson.dylib' (no such file), '/private/var/containers/Bundle/Application/FF2B21C5-C56D-4843-A33D-B05067617415/duolaimi.app/Frameworks/libtdjson.dylib' (no such file), '/private/var/containers/Bundle/Application/FF2B21C5-C56D-4843-A33D-B05067617415/duolaimi.app/Frameworks/libtdjson.dylib' (no such file), '/private/var/containers/Bundle/Application/FF2B21C5-C56D-4843-A33D-B05067617415/duolaimi.app/Frameworks/libtdjson.dylib' (no such file), '/usr/lib/swift/libtdjson.dylib' (no such file), '/private/var/containers/Bundle/Application/FF2B21C5-C56D-4843-A33D-B05067617415/duolaimi.app/Frameworks/libtdjson.dylib' (no su

**Comment by up9cloud** [comment]
You could just copy the files into bundle and set it up if you're not familiar with cocoapods. Check my comment below #2
